# Generated by Django 6.1.1 on 2026-09-04 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('entry_type', models.CharField(choices=[('REFLECT', 'Reflect'), ('TOILET', 'Toilet'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('FEELING', 'Feeling')], max_length=20)),
                ('input_from', models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver')], max_length=20)),
                ('analysed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_inputs', to='core.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='HeardAIMonthlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('ibd_symptoms', models.TextField()),
                ('food_sensitivities', models.TextField()),
                ('stress_levels', models.TextField()),
                ('emotional_wellbeing', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_entries', models.ManyToManyField(related_name='ai_analysis_entries', to='core.patiententry')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.patientrecord')),
            ],
        ),
    ]
