# Generated by Django 6.0.8 on 2026-09-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiententry',
            name='input_text',
        ),
        migrations.CreateModel(
            name='PatientFoodInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_description', models.CharField(max_length=255)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_inputs', to='core.patiententry')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInputMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('kilocalories_per100g', models.FloatField()),
                ('protein_per100g', models.FloatField()),
                ('carbohydrates_per100g', models.FloatField()),
                ('fats_per100g', models.FloatField()),
                ('fiber_per100g', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_food_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_macros', to='core.patientfoodinput')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReflectInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_text', models.TextField()),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflect_inputs', to='core.patiententry')),
            ],
        ),
    ]
