# Generated by Django 6.0.8 on 2026-09-05 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patiententry_input_text_patientfoodinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiententry',
            name='patient_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_entries', to='core.patientrecord'),
        ),
    ]
