# Generated by Django 6.0.8 on 2026-09-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patiententry_patient_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiententry',
            name='entry_type',
            field=models.CharField(choices=[('REFLECT', 'Reflect'), ('TOILET', 'Toilet'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine')], max_length=20),
        ),
        migrations.CreateModel(
            name='HeardAIreflectInputAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WORRYING', 'Worrying'), ('URGENT', 'Urgent')], default='pending', max_length=20)),
                ('color_status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20)),
                ('analysis_text', models.TextField()),
                ('patient_reflect_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.patientreflectinput')),
            ],
        ),
    ]
