# Generated by Django 6.0.8 on 2026-09-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patiententry_entry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeardAIFoodInputAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WORRYING', 'Worrying'), ('URGENT', 'Urgent')], default='pending', max_length=20)),
                ('color_status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20)),
                ('analysis_text', models.TextField()),
                ('patient_food_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.patientfoodinput')),
            ],
        ),
    ]
