# Generated by Django 6.0.8 on 2026-09-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_heardaifoodinputanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToiletInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stool_type', models.CharField(choices=[('NORMAL', 'Normal'), ('LOOSE', 'Loose'), ('WATERY', 'Watery'), ('HARD', 'Hard'), ('BLOODY', 'Bloody')], max_length=10)),
                ('stool_blood', models.BooleanField(default=False)),
                ('stool_urgency', models.BooleanField(default=False)),
                ('stool_at_night', models.BooleanField(default=False)),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_inputs', to='core.patiententry')),
            ],
        ),
    ]
