# Generated by Django 6.0.8 on 2026-09-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patienttoiletinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heardaifoodinputanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WORRYING', 'Worrying'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='patiententry',
            name='entry_type',
            field=models.CharField(choices=[('REFLECT', 'Reflect'), ('TOILET', 'Toilet'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('FEELING', 'Feeling'), ('PAIN_TOLERANCE', 'Pain Tolerance')], max_length=20),
        ),
        migrations.CreateModel(
            name='PatientBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField()),
                ('allergies', models.TextField()),
                ('medications', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='core.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFeelingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_type', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ANXIOUS', 'Anxious'), ('ANGRY', 'Angry'), ('TIRED', 'Tired')], max_length=10)),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_inputs', to='core.patiententry')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicineInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('side_effects', models.TextField()),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_inputs', to='core.patiententry')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPainToleranceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_level', models.IntegerField()),
                ('pain_location', models.CharField(max_length=100)),
                ('pain_description', models.TextField()),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pain_tolerance_inputs', to='core.patiententry')),
            ],
        ),
    ]
