# Generated by Django 6.0.8 on 2026-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_heardaifoodinputanalysis_analysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heardaireflectinputanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WORRYING', 'Worrying'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
    ]
