# Generated by Django 6.0.8 on 2026-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_heardaireflectinputanalysis_analysis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbackground',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientbackground',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patientbackground',
            name='medications',
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='diagnosis',
            field=models.CharField(choices=[('CROHNS', "Crohn's Disease"), ('UC', 'Ulcerative Colitis'), ('IBDU', 'IBD Unclassified')], default='CROHNS', max_length=20),
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='disease_behavior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='disease_location',
            field=models.CharField(blank=True, choices=[('SMALL_BOWEL', 'Small Bowel'), ('COLON', 'Colon'), ('ILEOCOLONIC', 'Ileocolonic'), ('UPPER_GI', 'Upper GI'), ('UNKNOWN', 'Unknown')], max_length=100),
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientbackground',
            name='surgeries',
            field=models.TextField(blank=True),
        ),
    ]
