# Generated by Django 6.0.8 on 2026-09-15 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_heardaitoiletinputanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeardAIConversationTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_text', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='ai_conversation_uploads/')),
                ('response_by', models.CharField(choices=[('AIMessage', 'AIMessage'), ('HumanMessage', 'HumanMessage')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_trails', to='core.patientrecord')),
            ],
        ),
    ]
