# Generated by Django 6.0.8 on 2026-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_heardaiconversationtrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttoiletinput',
            name='stool_type',
            field=models.CharField(choices=[('TYPE_1', 'Type 1 - Separate hard lumps'), ('TYPE_2', 'Type 2 - Sausage-shaped, hard and lumpy'), ('TYPE_3', 'Type 3 - Sausage-shaped with cracks'), ('TYPE_4', 'Type 4 - Smooth and soft'), ('TYPE_5', 'Type 5 - Soft blobs with clear edges'), ('TYPE_6', 'Type 6 - Fluffy, mushy pieces'), ('TYPE_7', 'Type 7 - Entirely liquid')], max_length=10),
        ),
    ]
