# Generated by Django 6.0.8 on 2026-09-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_patienttoiletinput_stool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientChampionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0)),
                ('habit_xp', models.PositiveIntegerField(default=0)),
                ('habit_level', models.PositiveIntegerField(default=1)),
                ('competency_xp', models.PositiveIntegerField(default=0)),
                ('competency_level', models.PositiveIntegerField(default=1)),
                ('resilience_xp', models.PositiveIntegerField(default=0)),
                ('resilience_level', models.PositiveIntegerField(default=1)),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='champion_stats', to='core.patientrecord')),
            ],
        ),
    ]
