# Generated by Django 6.0.8 on 2026-09-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patientchampionstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientchampionstats',
            options={'verbose_name': 'Patient Champion Stats', 'verbose_name_plural': 'Patient Champion Stats'},
        ),
    ]
