# Generated by Django 6.0.8 on 2026-09-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_patientchampionstats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heardaimonthlyanalysis',
            name='emotional_wellbeing',
        ),
        migrations.RemoveField(
            model_name='heardaimonthlyanalysis',
            name='food_sensitivities',
        ),
        migrations.RemoveField(
            model_name='heardaimonthlyanalysis',
            name='ibd_symptoms',
        ),
        migrations.RemoveField(
            model_name='heardaimonthlyanalysis',
            name='patient_entries',
        ),
        migrations.RemoveField(
            model_name='heardaimonthlyanalysis',
            name='stress_levels',
        ),
    ]
