# Generated by Django 6.0.8 on 2026-09-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_heardaimonthlyanalysis_emotional_wellbeing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiententry',
            name='analysed',
        ),
    ]
