# Generated by Django 6.0.8 on 2026-09-24 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_patiententry_analysed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorAppointmentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('reason_and_location_of_visit', models.TextField()),
                ('patient_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_inputs', to='core.patiententry')),
            ],
        ),
    ]
