# Generated by Django 6.0.8 on 2026-09-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_patientdoctorappointmentinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiententry',
            name='entry_type',
            field=models.CharField(choices=[('REFLECT', 'Reflect'), ('TOILET', 'Toilet'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('FEELING', 'Feeling'), ('PAIN_TOLERANCE', 'Pain Tolerance'), ('DOCTOR_APPOINTMENT', 'Doctor Appointment')], max_length=20),
        ),
    ]
